# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    categoriesFixtures: '%kernel.project_dir%/config/datasFixtures/categoriesFixtures.yaml'
    productsFixtures: '%kernel.project_dir%/config/datasFixtures/productsFixtures.yaml'
    categories_images: '%kernel.project_dir%/public/images/categories'
    products_images: '%kernel.project_dir%/public/images/products'
    app.publicKeyStripe: "%env(PUBLIC_KEY_STRIPE)%"
    app.secreteKeyStripe: "%env(SECRETE_KEY_STRIPE)%"
    stripe.webhook_secret: '%env(STRIPE_WEBHOOK_SECRET)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\NumberProductsFixtures:
        public: true

#    Stripe\Stripe:
#        arguments:
#            apiKey: "%env(SECRETE_KEY_STRIPE)%"
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
#    App\Twig\TwigGlobalSubscriber:
#        arguments:
#            - '@twig'
#            - '@doctrine.orm.entity_manager'
#    # add more service definitions when explicit configuration is needed
#    # please note that last definitions always *replace* previous ones